var testData =

    [
        {
            "DocID": "1120071870",
            "Title": "习近平治党方略的“良药”与“武器”",
            "NodeId": "11113319",
            "PubTime": "2016-12-07 11:38:13",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/07/c_1120069469.htm",
            "Abstract": "六中全会系列解读:看习近平的治党思路 两份文件 同一使命 党内监督没有禁区 铁帚除弊 明镜正冠",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "张芳玲",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 60,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120068680",
            "Title": "中医药，中国要！",
            "NodeId": "11113319",
            "PubTime": "2016-12-07 08:39:54",
            "LinkUrl": "http://fms.news.cn/swf/2016_qmtt/12_6_2016_zyy/index.html",
            "Abstract": "《中国的中医药》白皮书:中医药发展上升为国家战略 为啥说中医药是\"民族瑰宝\" 下一个屠呦呦何时出现",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "雷东瑞",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 61,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120058710",
            "Title": "习近平：提高改革整体效能 扩大改革受益面",
            "NodeId": "11113319",
            "PubTime": "2016-12-05 21:02:20",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/05/c_1120058658.htm",
            "Abstract": "习近平主持召开深改组会 李克强刘云山张高丽出席 3年30次会：习近平的全面深改“加速度” 新华社评论员",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120058075",
            "Title": "习近平在万里诞辰100周年座谈会上发表重要讲话",
            "NodeId": "11113319",
            "PubTime": "2016-12-05 18:45:57",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/05/c_1120057976.htm",
            "Abstract": "习近平:学习万里锐意改革、攻坚克难的政治担当 不忘初心、继续前进，创造无愧于人民的新业绩 全文",
            "keyword": null,
            "Editor": "丁峰",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 63,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120055786",
            "Title": "深港通开通 中国资本市场对外开放迎来新里程碑",
            "NodeId": "11113319",
            "PubTime": "2016-12-05 15:19:21",
            "LinkUrl": "http://www.xinhuanet.com/finance/zhuanti/huiyi/zt27.htm",
            "Abstract": "深圳和香港证券市场成功联通 哪些板块最诱人 中国资本市场开放脚步不会停止 沪港通及深港通大事记",
            "keyword": null,
            "Editor": "丁峰",
            "Author": "张立红",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120049356",
            "Title": "习近平:弘扬宪法精神推动宪法实施",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 16:57:43",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/04/c_1120049333.htm",
            "Abstract": "习近平:宪法是治国安邦的总章程 是党和人民意志的集中体现 2016年国家宪法日座谈会举行 新华社评论员",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 52,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120049356",
            "Title": "习近平:弘扬宪法精神推动宪法实施",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 16:57:43",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/04/c_1120049333.htm",
            "Abstract": "习近平:宪法是治国安邦的总章程 是党和人民意志的集中体现 2016年国家宪法日座谈会举行 新华社评论员",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 52,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120049356",
            "Title": "习近平:弘扬宪法精神推动宪法实施",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 16:57:43",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/04/c_1120049333.htm",
            "Abstract": "习近平:宪法是治国安邦的总章程 是党和人民意志的集中体现 2016年国家宪法日座谈会举行 新华社评论员",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 52,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120049356",
            "Title": "习近平:弘扬宪法精神推动宪法实施",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 16:57:43",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/04/c_1120049333.htm",
            "Abstract": "习近平:宪法是治国安邦的总章程 是党和人民意志的集中体现 2016年国家宪法日座谈会举行 新华社评论员",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 52,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120049356",
            "Title": "习近平:弘扬宪法精神推动宪法实施",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 16:57:43",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/04/c_1120049333.htm",
            "Abstract": "习近平:宪法是治国安邦的总章程 是党和人民意志的集中体现 2016年国家宪法日座谈会举行 新华社评论员",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 52,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120049356",
            "Title": "习近平:弘扬宪法精神推动宪法实施",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 16:57:43",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/04/c_1120049333.htm",
            "Abstract": "习近平:宪法是治国安邦的总章程 是党和人民意志的集中体现 2016年国家宪法日座谈会举行 新华社评论员",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 52,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120049356",
            "Title": "习近平:弘扬宪法精神推动宪法实施",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 16:57:43",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/04/c_1120049333.htm",
            "Abstract": "习近平:宪法是治国安邦的总章程 是党和人民意志的集中体现 2016年国家宪法日座谈会举行 新华社评论员",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 52,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120048901",
            "Title": "习近平:发展是人类社会永恒的主题",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 14:20:26",
            "LinkUrl": "http://www.xinhuanet.com/world/1611tfsj18/index.htm",
            "Abstract": "习近平致信祝贺\"纪念《发展权利宣言》通过30周年国际研讨会\"开幕 贺信全文 书写实现人民发展权新篇章",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "王萌萌",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 51,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120047710",
            "Title": "中央八项规定出台四周年:清风扬正气 奋进正当时",
            "NodeId": "11113319",
            "PubTime": "2016-12-04 09:59:35",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120046742.htm",
            "Abstract": "四年来查处问题14万余起、处理人数19万余人 图解中央\"硬杠杠\" 新华社评论员：久久为功，作风建设永远在路上",
            "keyword": null,
            "Editor": "张立红",
            "Author": "张立红",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120046546",
            "Title": "习近平：扎实推进军队规模结构和力量编成改革",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 18:38:10",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120046523.htm",
            "Abstract": "习近平:坚定不移走中国特色强军之路 军改一年间,习近平这样排兵布阵 广大官兵:拥护改革 图解",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 63,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120046546",
            "Title": "习近平：扎实推进军队规模结构和力量编成改革",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 18:38:10",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120046523.htm",
            "Abstract": "习近平:坚定不移走中国特色强军之路 军改一年间,习近平这样排兵布阵 广大官兵:拥护改革 图解",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 63,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120046546",
            "Title": "习近平：扎实推进军队规模结构和力量编成改革",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 18:38:10",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120046523.htm",
            "Abstract": "习近平:坚定不移走中国特色强军之路 军改一年间,习近平这样排兵布阵 广大官兵:拥护改革 图解",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 63,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120046546",
            "Title": "习近平：扎实推进军队规模结构和力量编成改革",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 18:38:10",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120046523.htm",
            "Abstract": "习近平:坚定不移走中国特色强军之路 军改一年间,习近平这样排兵布阵 广大官兵:拥护改革 图解",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 63,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120046222",
            "Title": "新华社评论员：久久为功，作风建设永远在路上",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 15:53:08",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120044716.htm",
            "Abstract": "习近平主持政治局会议 审议规范领导人待遇等文件 总书记怎样抓作风建设？ 激扬正气定乾坤 漫说新变化",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 61,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120046222",
            "Title": "新华社评论员：久久为功，作风建设永远在路上",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 15:53:08",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120044716.htm",
            "Abstract": "习近平主持政治局会议 审议规范领导人待遇等文件 总书记怎样抓作风建设？ 激扬正气定乾坤 漫说新变化",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": 1,
            "Attr": 61,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120046222",
            "Title": "新华社评论员：久久为功，作风建设永远在路上",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 15:53:08",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120044716.htm",
            "Abstract": "习近平主持政治局会议 审议规范领导人待遇等文件 总书记怎样抓作风建设？ 激扬正气定乾坤 漫说新变化",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": 2,
            "Attr": 61,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120046222",
            "Title": "新华社评论员：久久为功，作风建设永远在路上",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 15:53:08",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120044716.htm",
            "Abstract": "习近平主持政治局会议 审议规范领导人待遇等文件 总书记怎样抓作风建设？ 激扬正气定乾坤 漫说新变化",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": 3,
            "Attr": 61,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
                {
            "DocID": "1120046222",
            "Title": "新华社评论员：久久为功，作风建设永远在路上",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 15:53:08",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120044716.htm",
            "Abstract": "习近平主持政治局会议 审议规范领导人待遇等文件 总书记怎样抓作风建设？ 激扬正气定乾坤 漫说新变化",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": 1,
            "Attr": 61,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
                {
            "DocID": "1120046222",
            "Title": "新华社评论员：久久为功，作风建设永远在路上",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 15:53:08",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120044716.htm",
            "Abstract": "习近平主持政治局会议 审议规范领导人待遇等文件 总书记怎样抓作风建设？ 激扬正气定乾坤 漫说新变化",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": 1,
            "Attr": 61,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120046222",
            "Title": "新华社评论员：久久为功，作风建设永远在路上",
            "NodeId": "11113319",
            "PubTime": "2016-12-03 15:53:08",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/03/c_1120044716.htm",
            "Abstract": "习近平主持政治局会议 审议规范领导人待遇等文件 总书记怎样抓作风建设？ 激扬正气定乾坤 漫说新变化",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": 3,
            "Attr": 61,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120043272",
            "Title": "习近平会见美国前国务卿基辛格",
            "NodeId": "11113319",
            "PubTime": "2016-12-02 22:06:22",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/02/c_1120043172.htm",
            "Abstract": "习近平:中美之间共同利益远大于分歧 坚持不冲突不对抗、相互尊重、合作共赢 推进中美新型大国关系建设",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120042649",
            "Title": "习近平对生态文明建设作重要指示 李克强作批示",
            "NodeId": "11113319",
            "PubTime": "2016-12-02 18:08:27",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/02/c_1120042543.htm",
            "Abstract": "张高丽出席生态文明建设工作会并讲话 制度建设是生态文明建设重中之重 绿色发展走向生态文明新时代",
            "keyword": null,
            "Editor": "雷东瑞",
            "Author": "雷东瑞",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120039635",
            "Title": "习近平就哇集拉隆功就任泰国国王致贺电",
            "NodeId": "11113319",
            "PubTime": "2016-12-02 11:57:11",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/02/c_1120039499.htm",
            "Abstract": "习近平：推动两国关系不断迈上新台阶 承受厚望 泰国新国王正式登基 肩负哪些使命?",
            "keyword": null,
            "Editor": "丁峰",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120036145",
            "Title": "走，到农村创业去！",
            "NodeId": "11113319",
            "PubTime": "2016-12-02 09:38:17",
            "LinkUrl": "http://fms.news.cn/swf/2016_qmtt/12_1_2016_ygl/index.html",
            "Abstract": "“新农人”返乡下乡渐成热潮 全国返乡创业创新人数累计达570多万 雁归来——农民工陈俭平返乡创业记",
            "keyword": null,
            "Editor": "熊红祥",
            "Author": "熊红祥",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120035488",
            "Title": "习近平同塞拉利昂总统科罗马举行会谈",
            "NodeId": "11113319",
            "PubTime": "2016-12-01 22:04:29",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/01/c_1120035198.htm",
            "Abstract": "两国元首一致决定 建立中塞全面战略合作伙伴关系 双方要在国际上加强配合协作，维护非洲团结",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120035084",
            "Title": "习近平：携手打造牢不可破的中老命运共同体",
            "NodeId": "11113319",
            "PubTime": "2016-12-01 19:28:23",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/01/c_1120034949.htm",
            "Abstract": "习近平会见老挝总理通伦 巩固双边关系良好势头 拓展全面战略合作  两党两国领导人要及时就重大问题交换意见",
            "keyword": null,
            "Editor": "张芳玲",
            "Author": "张芳玲",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120029944",
            "Title": "《发展权：中国的理念、实践与贡献》白皮书发表",
            "NodeId": "11113319",
            "PubTime": "2016-12-01 11:27:50",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-12/01/c_1120029207.htm",
            "Abstract": "巨大成就开创人类人权保障新道路 人均预期寿命提高到76.34岁 对外援助4000亿元 书写实现人民发展权的新篇章",
            "keyword": null,
            "Editor": "熊红祥",
            "Author": "熊红祥",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120025989",
            "Title": "习近平给广大文艺工作者提出四点希望",
            "NodeId": "11113319",
            "PubTime": "2016-11-30 23:14:26",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/30/c_1120025319.htm",
            "Abstract": "文代会作代会开幕 习近平发表重要讲话 文艺工作者看过来,习近平有重托 热烈反响 新华社评论员:筑就文艺高峰",
            "keyword": null,
            "Editor": "马俊卿",
            "Author": "袁喆",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120025259",
            "Title": "习近平：筑就中华民族伟大复兴时代文艺高峰",
            "NodeId": "11113319",
            "PubTime": "2016-11-30 18:16:22",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/30/c_1120025224.htm",
            "Abstract": "文代会、作代会开幕 习近平出席大会并发表重要讲话 全文 李克强张德江俞正声刘云山王岐山张高丽出席",
            "keyword": null,
            "Editor": "刘笑冬",
            "Author": "袁喆",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120024573",
            "Title": "习近平就玻利维亚民航包机失事致慰问电",
            "NodeId": "11113319",
            "PubTime": "2016-11-30 17:45:16",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/30/c_1120024431.htm",
            "Abstract": "习近平向巴西总统特梅尔、玻利维亚总统莫拉莱斯致慰问电 一载有巴西球员的玻利维亚客机失事 71人遇难",
            "keyword": null,
            "Editor": "袁喆",
            "Author": "丁峰",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120016551",
            "Title": "纪念朱德诞辰座谈会举行 习近平发表重要讲话",
            "NodeId": "11113319",
            "PubTime": "2016-11-29 20:18:50",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/29/c_1120016516.htm",
            "Abstract": "习近平:继续把革命前辈开创的伟大事业推向前进 全文 李克强俞正声刘云山王岐山张高丽出席 张德江主持",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120012404",
            "Title": "习近平赴古巴驻华使馆吊唁菲德尔·卡斯特罗逝世",
            "NodeId": "11113319",
            "PubTime": "2016-11-29 12:13:05",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/29/c_1120013721.htm",
            "Abstract": "习近平就卡斯特罗逝世致唁电 特写:为共产主义理想奋斗不息的传奇硬汉 新华社记者眼中的卡斯特罗 专题",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "熊红祥",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": "1120012404_1480406245195_title.gif",
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120011691",
            "Title": "\"中国梦\"提出四周年：向着伟大复兴梦想继续前进",
            "NodeId": "11113319",
            "PubTime": "2016-11-29 11:26:36",
            "LinkUrl": "http://fms.news.cn/swf/2016_qmtt/11_28_2016_zgm/index.html",
            "Abstract": "逐梦之路更宽广 圆梦之基更牢固 追梦之心更自信 新华社评论员 系列网评 中国梦走向世界的豪迈与担当",
            "keyword": null,
            "Editor": "陈淑君",
            "Author": "陈淑君",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1120001987",
            "Title": "军改一年间，习近平这样排兵布阵",
            "NodeId": "11113319",
            "PubTime": "2016-11-28 10:09:36",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/28/c_1120001069.htm",
            "Abstract": "视频:穿军装的习近平 习主席授过的旗 书写合格答卷 新成立部队的昨天今天明天 一图读懂军改 专题",
            "keyword": null,
            "Editor": "周庚虎",
            "Author": "陈淑君",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119996204",
            "Title": "习近平就古巴革命领袖菲德尔·卡斯特罗逝世致唁电",
            "NodeId": "11113319",
            "PubTime": "2016-11-26 21:17:54",
            "LinkUrl": "http://news.xinhuanet.com/world/2016-11/26/c_1119996505.htm",
            "Abstract": "习近平:这个时代的伟大人物 为共产主义理想奋斗不息 离去影响几何 新华社记者眼中的卡斯特罗 专题",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "熊红祥",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119996055",
            "Title": "军改一年间：书写时代大考的合格答卷",
            "NodeId": "11113319",
            "PubTime": "2016-11-26 18:23:00",
            "LinkUrl": "http://news.xinhuanet.com/mil/2016-11/26/c_129379475.htm",
            "Abstract": "习近平的强军之道 从三次视察看习近平的治军思路 图刊：练兵场上展英姿 一图带你读懂军改 专题",
            "keyword": null,
            "Editor": "张芳玲",
            "Author": "周庚虎",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119994711",
            "Title": "军改一年间：改革强军迈步新长征",
            "NodeId": "11113319",
            "PubTime": "2016-11-26 09:52:33",
            "LinkUrl": "http://news.xinhuanet.com/mil/2016-11/26/c_129379475.htm",
            "Abstract": "全军和武警部队积极投身改革强军实践述评 改革强军成为军心所向 习近平治军思路 强军之道 带你看军改",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119993479",
            "Title": "受权发布：中华人民共和国无线电管理条例",
            "NodeId": "11113319",
            "PubTime": "2016-11-25 21:05:45",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/25/c_1119993275.htm",
            "Abstract": "任何单位或者个人不得擅自使用无线电频率 根据需要国家可以实施无线电管制 惩戒“伪基站” 答问",
            "keyword": null,
            "Editor": "熊红祥",
            "Author": "熊红祥",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119985237",
            "Title": "习近平对江西电厂坍塌事故作重要指示 李克强批示",
            "NodeId": "11113319",
            "PubTime": "2016-11-24 19:31:51",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/24/c_1119985192.htm",
            "Abstract": "要求做好救援救治善后处置工作 确保人民群众生命财产安全 74人遇难 13人被控制 救援 现场直击 视频",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "雷东瑞",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119983481",
            "Title": "中组部就关于新形势下党内政治生活的若干准则答问",
            "NodeId": "11113319",
            "PubTime": "2016-11-24 15:41:24",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/24/c_1119981605.htm",
            "Abstract": "1980年《准则》主要原则和规定依然适用 为什么要制定一个新的准则 新举措和新观点如何贯彻落实 专题",
            "keyword": null,
            "Editor": "孙佳悦",
            "Author": "孙佳悦",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119980745",
            "Title": "新常态、新经济、新动能 “2016国是论坛”开幕",
            "NodeId": "11113319",
            "PubTime": "2016-11-24 10:53:03",
            "LinkUrl": "http://news.cn/fortune/guoshi2016/index.htm",
            "Abstract": "新动能加快成长 新经济迸发活力 房地产税出台应慎重 人民币汇率短期波动 长期看仍将升值 专题",
            "keyword": null,
            "Editor": "孙佳悦",
            "Author": "孙佳悦",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119976549",
            "Title": "李克强考察上海自贸区:打造改革创新开放的新标杆",
            "NodeId": "11113319",
            "PubTime": "2016-11-23 20:15:43",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/23/c_1119976513.htm",
            "Abstract": "上海自贸区3岁了 总理又来啦！中国仍是全球最佳投资目的地 这场\"放管服\"座谈会为何放在上海自贸区开",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "雷东瑞",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119971259",
            "Title": "总理为何对这两家上海小食店念念不忘",
            "NodeId": "11113319",
            "PubTime": "2016-11-23 10:41:40",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/23/c_1119971225.htm",
            "Abstract": "李克强：以壮士断腕精神把\"放管服\"改革向纵深推进 用政府自身一时的痛换来人民长远的利",
            "keyword": null,
            "Editor": "孙佳悦",
            "Author": "孙佳悦",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119967243",
            "Title": "李克强：用政府自身一时的痛换来人民长远的利",
            "NodeId": "11113319",
            "PubTime": "2016-11-22 22:07:16",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/22/c_1119966987.htm",
            "Abstract": "李克强：以壮士断腕精神把\"放管服\"改革向纵深推进 更有效的管就可以更多的放 管得好才能放得活",
            "keyword": null,
            "Editor": "张芳玲",
            "Author": "张芳玲",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119952265",
            "Title": "李克强出席第九届全球健康促进大会开幕式并致辞",
            "NodeId": "11113319",
            "PubTime": "2016-11-21 10:27:28",
            "LinkUrl": "http://www.sh.xinhuanet.com/zhuanti2016/live20161121/index.htm",
            "Abstract": "李克强:让医务人员得到社会尊重和应有报酬 见陈冯富珍等国际组织负责人 考察上海自贸区 专题",
            "keyword": null,
            "Editor": "孙佳悦",
            "Author": "孙佳悦",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119958324",
            "Title": "李克强出席第九届全球健康促进大会开幕式并致辞",
            "NodeId": "11113319",
            "PubTime": "2016-11-21 22:01:01",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/21/c_1119958273.htm",
            "Abstract": "回放 李克强:让医务人员得到尊重和应有报酬 见陈冯富珍等国际组织负责人 考察上海自贸区 GE中国 专题",
            "keyword": null,
            "Editor": "钱中兵",
            "Author": "陈淑君",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119945278",
            "Title": "国家主席习近平抵达利马",
            "NodeId": "11113319",
            "PubTime": "2016-11-19 09:22:32",
            "LinkUrl": "http://news.xinhuanet.com/world/2016-11/19/c_1119944754.htm",
            "Abstract": "习近平同科雷亚共同出席中厄合作项目揭牌仪式 会见厄瓜多尔国民代表大会主席里瓦德内拉 中国风",
            "keyword": null,
            "Editor": "张立红",
            "Author": "张立红",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119941804",
            "Title": "天宫二号和神舟十一号载人飞行任务圆满成功",
            "NodeId": "11113319",
            "PubTime": "2016-11-18 15:01:23",
            "LinkUrl": "http://www.xinhuanet.com/politics/zhibo1/sz1120161118/index.htm",
            "Abstract": "中共中央、国务院、中央军委贺电 全文 发布会回放 航天员身体状态良好 新华社评论员 新里程碑 专题",
            "keyword": null,
            "Editor": "孙佳悦",
            "Author": "张立红",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119944261",
            "Title": "李克强：全面有效保护妇女儿童合法权益",
            "NodeId": "11113319",
            "PubTime": "2016-11-18 21:02:32",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/18/c_1119944218.htm",
            "Abstract": "李克强出席妇女儿童工作会并讲话 确保妇女享有与男子平等的土地权益 为所有家庭孩子创造公平教育条件",
            "keyword": null,
            "Editor": "孙佳悦",
            "Author": "孙佳悦",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119937905",
            "Title": "直播:神舟十一号飞船返回",
            "NodeId": "11113319",
            "PubTime": "2016-11-18 13:06:01",
            "LinkUrl": "http://www.xinhuanet.com/politics/zhibo1/sz1120161118/index.htm",
            "Abstract": "张高丽宣读中共中央、国务院、中央军委贺电 天地科普课 天地采访 太空日记 天马行空33天 十问 专题",
            "keyword": null,
            "Editor": "张立红",
            "Author": "张立红",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119936830",
            "Title": "习近平抵达基多开始对厄瓜多尔进行国事访问",
            "NodeId": "11113319",
            "PubTime": "2016-11-18 07:39:05",
            "LinkUrl": "http://www.xinhuanet.com/world/cnleaders/xijinping/xjpcf1611/index.htm",
            "Abstract": "习近平在厄瓜多尔媒体发表署名文章 引厄民众共鸣 《习近平谈治国理政》在厄瓜多尔图书展展销",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119933895",
            "Title": "习近平会见意大利总理",
            "NodeId": "11113319",
            "PubTime": "2016-11-17 15:27:39",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/17/c_1119927888.htm",
            "Abstract": "习近平:意大利是中国在欧盟内值得信赖的好朋友和重要合作伙伴 充实中意全面战略伙伴关系内涵",
            "keyword": null,
            "Editor": "陈淑君",
            "Author": "陈淑君",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119925767",
            "Title": "习近平：让互联网更好造福人类",
            "NodeId": "11113319",
            "PubTime": "2016-11-16 16:40:55",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/16/c_1119925089.htm",
            "Abstract": "第三届世界互联网大会开幕 习近平视频讲话 全文 热烈反响 刘云山致辞 全体会议 新华社评论员 专题",
            "keyword": null,
            "Editor": "陈淑君",
            "Author": "孙佳悦",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119923203",
            "Title": "第三届世界互联网大会开幕 习近平发表视频讲话",
            "NodeId": "11113319",
            "PubTime": "2016-11-16 11:13:57",
            "LinkUrl": "http://www.xinhuanet.com/world/2016WIC/2016WICopening/index.htm",
            "Abstract": "习近平:让互联网更好造福人类 刘云山发表致辞 互联网世界迎来\"乌镇时间\" 助力中国跨越式发展 专题",
            "keyword": null,
            "Editor": "张立红",
            "Author": "张立红",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119921089",
            "Title": "第三届世界互联网大会开幕",
            "NodeId": "11113319",
            "PubTime": "2016-11-16 10:27:32",
            "LinkUrl": "http://www.xinhuanet.com/world/2016WIC/2016WICopening/index.htm",
            "Abstract": "习近平通过视频发表讲话 刘云山发表致辞 互联网世界迎来\"乌镇时间\" 助中国跨越式发展 专题",
            "keyword": null,
            "Editor": "张立红",
            "Author": "张立红",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119911255",
            "Title": "“中国版”地方政府财政重整计划到底怎么整",
            "NodeId": "11113319",
            "PubTime": "2016-11-14 22:29:03",
            "LinkUrl": "http://www.xinhuanet.com/jrgz/20161114a/index.htm",
            "Abstract": "国办印发《地方政府性债务风险应急处置预案》 四维透视 超16万亿地方债风险如何控 借钱先想好怎么还",
            "keyword": null,
            "Editor": "陈淑君",
            "Author": "孙佳悦",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119910955",
            "Title": "习近平签署命令 追授张超荣誉称号",
            "NodeId": "11113319",
            "PubTime": "2016-11-14 19:43:21",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/14/c_1119909045.htm",
            "Abstract": "追授张超“逐梦海天的强军先锋”荣誉称号 海军航母舰载战斗机飞行员训练中英勇牺牲 魂系深蓝海天间",
            "keyword": null,
            "Editor": "孙佳悦",
            "Author": "孙佳悦",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119904127",
            "Title": "求解“看病难”:拿什么拯救你，一“号”难求",
            "NodeId": "11113319",
            "PubTime": "2016-11-14 09:07:45",
            "LinkUrl": "http://www.jjckb.cn/yhnqindex.htm",
            "Abstract": "号贩子转战网络“倒号升级” 医管局局长暗访碰到了什么尴尬事?  北京市属医院挂号攻略",
            "keyword": null,
            "Editor": "张立红",
            "Author": "张立红",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119902193",
            "Title": "习近平讲话引起热烈反响：共同反对\"台独\"分裂",
            "NodeId": "11113319",
            "PubTime": "2016-11-13 17:03:59",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/12/c_1119899563.htm",
            "Abstract": "孙中山诞辰150周年纪念大会 习近平发表重要讲话 全文 侧记 新华社评论员 同心振兴中华",
            "keyword": null,
            "Editor": "陈淑君",
            "Author": "马轶群",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        },
        {
            "DocID": "1119899504",
            "Title": "习近平在孙中山诞辰纪念大会上讲话引发强烈反响",
            "NodeId": "11113319",
            "PubTime": "2016-11-12 16:24:10",
            "LinkUrl": "http://news.xinhuanet.com/politics/2016-11/11/c_1119897598.htm",
            "Abstract": "孙中山诞辰150周年纪念大会 习近平发表重要讲话 全文 共同反对\"台独\"分裂势力 侧记 新华社评论员",
            "keyword": null,
            "Editor": "刘晓朋",
            "Author": "刘晓朋",
            "IsLink": "1",
            "SourceName": null,
            "PicLinks": null,
            "IsMoreImg": null,
            "imgarray": null,
            "SubTitle": null,
            "Attr": 62,
            "m4v": null,
            "tarray": [],
            "uarray": []
        }
    ]

